version: '3'
services:
  api-server:
    build: .
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules/bcrypt/
    networks:
      - bkmrkd
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 4000:80
    networks:
      - bkmrkd

networks:
  bkmrkd:
    driver: bridge