version: '3'
services:
  api-server:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
      - /app/node_modules/bcrypt/
    networks:
      - bkmrkd
  
networks:
  bkmrkd:
    driver: bridge
