version: '3'
services:
  api-server:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
      - /app/node_modules/bcrypt/
    networks:
      - bkmrkd

  redis-server:
    image: bitnami/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    restart: always
    networks:
      - bkmrkd

networks:
  bkmrkd:
    driver: bridge
