version: '3'
services:
  api-server:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend:/app
      - /app/node_modules/bcrypt/
    networks:
      - bkmrkd
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    ports:
      - 5000:5000
    networks:
      - bkmrkd
networks:
  bkmrkd:
    driver: bridge